### ISSUE TITLE
Chrome Recognizes the Page in a Different Language.

### ISSUE THREAD

**Issue by benjaminmcd** [everylittlebit/2702Website#17] opened 2016-12-05 22:31 UTC

**Comment by everylittlebit** [comment] 2016-12-21 00:31
This is caused by the former sample text.

**Comment by everylittlebit** [comment] 2016-12-21 00:32
Fixed in 23fe49abe43b0bb22ea074ab5bcd6c26cde9548c

**Closed** 2016-12-21 00:33 UTC
